log:
  debug: true

redis:
  addr: "localhost:6379"

mq:
  kafka:
    network: "tcp"
    addr: "localhost:9092"

etcd:
  addrs:
    - "127.0.0.1:2379"
  connectTimeout: "1s"
  secure: false

cache:
  local:
    capacity: 1000000

server:
  governor:
    host: 0.0.0.0
    port: 9003
  websocket:
    host: "0.0.0.0"
    port: 9002
    serializer: "proto"

backend:
  services:
    etcdKey: "gateway.backend.services"

pushMessageEvent:
  partitions: 2
  topic: "push_message_event"

retryStrategy:
  initRetryInterval: 1000000000
  maxRetryInterval: 3000000000
  maxRetries: 3

linkEvent:
  onReceiveTimeout: 3000000000