apiVersion: 1
groups:
  - orgId: 1
    name: 网关节点再均衡
    folder: 网关告警规则
    interval: 10s
    rules:
      - uid: eepe22i990a2oa
        title: gw-1-智能再均衡
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 21600
              to: 0
            datasourceUid: prometheus-uid
            model:
              adhocFilters: []
              datasource:
                type: prometheus
                uid: prometheus-uid
              disableTextWrap: false
              editorMode: builder
              expr: sum by(instance, job, node_id) (websocket_gateway_online_users{job="websocket-gateway", node_id="gw-1"})
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              interval: ""
              intervalMs: 15000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 3
                    type: gte
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: gateway-dashboard-uid
        panelId: 1
        noDataState: NoData
        execErrState: Error
        annotations:
          __dashboardUid__: gateway-dashboard-uid
          __panelId__: "1"
        isPaused: false
        notification_settings:
          receiver: gw-1-智能再均衡
      - uid: fepe26maddr7kd
        title: gw-2-扩容再均衡
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 21600
              to: 0
            datasourceUid: prometheus-uid
            model:
              adhocFilters: []
              datasource:
                type: prometheus
                uid: prometheus-uid
              disableTextWrap: false
              editorMode: builder
              expr: sum by(instance, job, node_id) (websocket_gateway_online_users{job="websocket-gateway", node_id="gw-2"})
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              interval: ""
              intervalMs: 15000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 3
                    type: gte
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: gateway-dashboard-uid
        panelId: 1
        noDataState: NoData
        execErrState: Error
        annotations:
          __dashboardUid__: gateway-dashboard-uid
          __panelId__: "1"
        isPaused: false
        notification_settings:
          receiver: gw-2-扩容再均衡
