// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitee.com/flycash/ws-gateway"
	"gitee.com/flycash/ws-gateway/ioc"
	"gitee.com/flycash/ws-gateway/pkg/jwt"
	"github.com/ecodeclub/ecache"
	"github.com/ecodeclub/mq-api"
)

// Injectors from wire.go:

func InitApp() App {
	mq := ioc.InitMQ()
	cmdable := ioc.InitRedisCmd()
	cache := ioc.InitRedisCache(cmdable)
	userToken := ioc.InitUserToken()
	codec := ioc.InitSerializer()
	component := ioc.InitEtcdClient()
	linkEventHandlerWrapper := ioc.InitLinkEventHandlerWrapper(cache, codec, component, mq)
	v := convertToWebsocketComponents(mq, cache, userToken, linkEventHandlerWrapper)
	app := App{
		OrderServer: v,
	}
	return app
}

// wire.go:

type App struct {
	OrderServer []gateway.Server
}

func convertToWebsocketComponents(
	messageQueue mq.MQ,
	c ecache.Cache,
	userToken *jwt.UserToken,
	wrapper *gateway.LinkEventHandlerWrapper,
) []gateway.Server {
	configKey := "server.websocket"
	s := make([]gateway.Server, 0, 1)

	s = append(s, ioc.InitWebSocketServer(configKey, messageQueue, c, userToken, wrapper))

	return s
}
