// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitee.com/flycash/ws-gateway"
	"gitee.com/flycash/ws-gateway/ioc"
	"gitee.com/flycash/ws-gateway/pkg/codec"
	"gitee.com/flycash/ws-gateway/pkg/jwt"
	"github.com/ecodeclub/ecache"
	"github.com/ecodeclub/mq-api"
	"github.com/ego-component/eetcd"
	"github.com/gotomicro/ego/core/econf"
)

// Injectors from wire.go:

func InitApp() App {
	mq := ioc.InitMQ()
	cache := ioc.InitLocalCache()
	userToken := ioc.InitUserToken()
	component := ioc.InitEtcdClient()
	v := convertToWebsocketComponents(mq, cache, userToken, component)
	app := App{
		OrderServer: v,
	}
	return app
}

// wire.go:

type App struct {
	OrderServer []gateway.Server
}

func convertToWebsocketComponents(
	messageQueue mq.MQ,
	localCache ecache.Cache,
	userToken *jwt.UserToken,
	etcdClient *eetcd.Component,
) []gateway.Server {
	configKey := "server.websocket"
	config := econf.GetStringMap(configKey)
	serializer, ok := config["serializer"].(string)
	if !ok {
		panic("server.websocket.serializer配置解析错误")
	}
	delete(config, "serializer")

	codecMapping := map[string]codec.Codec{
		"json":  codec.NewIgnoreAnyProtoFieldJSONCodec(),
		"proto": codec.NewProtoCodec(),
	}

	s := make([]gateway.Server, 0, len(config))

	s = append(s, ioc.InitWebSocketServer(configKey, messageQueue, localCache, userToken, codecMapping[serializer], etcdClient))

	return s
}
